apiVersion: apps/v1
kind: Deployment
metadata:
  name: quillbot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quillbot
  template:
    metadata:
      labels:
        app: quillbot
    spec:
      containers:
      - name: quillbot-container   # MUST match Jenkins
        image: imakhileshdev5/quillbotimage:latest
        ports:
        - containerPort: 3000
