apiVersion: apps/v1
kind: Deployment
metadata:
  name: quillbot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quillbot
  template:
    metadata:
      labels:
        app: quillbot
    spec:
      containers:
      - name: quillbot
        image: imakhileshdev5/quillimage
        ports:
        - containerPort: 80
